baseURL = 'https://cranes-Captiv.github.io/blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'dead-simple'
tags = [
    "starter-tag",
    "test-tag",
]

[taxonomies]
  tag = "tags"
  category = "categories"


[menu]
  [[menu.main]]
    name = "Tags[t]"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    name = "Home[h]"
    url = "/"
    weight = 10
